
import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Frame1 extends javax.swing.JFrame {
    int [][] values;
    private JLabel[][] jl=null;
    Random rd=null;
    int score_user;
    Color c0,c2,c4,c8,c16,c32,c64,c128,c256,c512,c1024,c2048;
    
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        jl=new JLabel[5][5];
        values=new int[5][5];
        rd=new Random();
        score_user=0;
        this.setTitle("2048");
        this.assign_respective_labels();
        
        c0=new Color(232,76,101);
        c2=new Color(237, 225, 228);
        c4=new Color(224, 217, 205);
        c8=new Color(173, 109, 77);
        c16=new Color(211,148,69);
        c32=new Color(152,80,56);
        c64=new Color(199,78,56);
        c128=new Color(214,167,87);
        c256=new Color(235,154,87);
        c512=new Color(247,197,43);
        c1024=new Color(247,157,43);
        c2048=new Color(239,183,101);
        
        
        for(int i=0;i<values.length;++i)
        {
            for(int j=0;j<values[i].length;++j)
            {
                //jl[i][j].setText("0");
                //jl[i][j].setOpaque(true);
                values[i][j]=0;
            }
        }
        
       // this.store_values_from_label();
        this.generating_new_number();
        this.show_values_into_labels();
        
        
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();
        btnUP = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_00 = new javax.swing.JLabel();
        jLabel_01 = new javax.swing.JLabel();
        jLabel_02 = new javax.swing.JLabel();
        jLabel_03 = new javax.swing.JLabel();
        jLabel_04 = new javax.swing.JLabel();
        jLabel_40 = new javax.swing.JLabel();
        jLabel_41 = new javax.swing.JLabel();
        jLabel_42 = new javax.swing.JLabel();
        jLabel_43 = new javax.swing.JLabel();
        jLabel_44 = new javax.swing.JLabel();
        jLabel_10 = new javax.swing.JLabel();
        jLabel_11 = new javax.swing.JLabel();
        jLabel_12 = new javax.swing.JLabel();
        jLabel_13 = new javax.swing.JLabel();
        jLabel_14 = new javax.swing.JLabel();
        jLabel_20 = new javax.swing.JLabel();
        jLabel_21 = new javax.swing.JLabel();
        jLabel_22 = new javax.swing.JLabel();
        jLabel_23 = new javax.swing.JLabel();
        jLabel_24 = new javax.swing.JLabel();
        jLabel_30 = new javax.swing.JLabel();
        jLabel_31 = new javax.swing.JLabel();
        jLabel_32 = new javax.swing.JLabel();
        jLabel_33 = new javax.swing.JLabel();
        jLabel_34 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new java.awt.GridLayout(1, 0));

        btnUP.setText("Up");
        btnUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPActionPerformed(evt);
            }
        });

        btnLeft.setText("Left");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnRight.setText("Right");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnDown.setText("Down");
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(btnDown)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(btnUP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnRight)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnUP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeft)
                    .addComponent(btnRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDown)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCORE");

        score.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText("0000");

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 18, 0, 18, 0, 18, 0, 18, 0};
        jPanel1Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel5.setLayout(jPanel1Layout);

        jLabel_00.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_00.setText("2048");
        jLabel_00.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel5.add(jLabel_00, gridBagConstraints);

        jLabel_01.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_01.setText("2048");
        jLabel_01.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jLabel_01, gridBagConstraints);

        jLabel_02.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_02.setText("2048");
        jLabel_02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jLabel_02, gridBagConstraints);

        jLabel_03.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_03.setText("2048");
        jLabel_03.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jLabel_03, gridBagConstraints);

        jLabel_04.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_04.setText("2048");
        jLabel_04.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jLabel_04, gridBagConstraints);

        jLabel_40.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_40.setText("2048");
        jLabel_40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel5.add(jLabel_40, gridBagConstraints);

        jLabel_41.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_41.setText("2048");
        jLabel_41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel5.add(jLabel_41, gridBagConstraints);

        jLabel_42.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_42.setText("2048");
        jLabel_42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanel5.add(jLabel_42, gridBagConstraints);

        jLabel_43.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_43.setText("2048");
        jLabel_43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel5.add(jLabel_43, gridBagConstraints);

        jLabel_44.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_44.setText("2048");
        jLabel_44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        jPanel5.add(jLabel_44, gridBagConstraints);

        jLabel_10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_10.setText("2048");
        jLabel_10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel_10, gridBagConstraints);

        jLabel_11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_11.setText("2048");
        jLabel_11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel_11, gridBagConstraints);

        jLabel_12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_12.setText("2048");
        jLabel_12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel_12, gridBagConstraints);

        jLabel_13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_13.setText("2048");
        jLabel_13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel_13, gridBagConstraints);

        jLabel_14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_14.setText("2048");
        jLabel_14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel_14, gridBagConstraints);

        jLabel_20.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_20.setText("2048");
        jLabel_20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jLabel_20, gridBagConstraints);

        jLabel_21.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_21.setText("2048");
        jLabel_21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jLabel_21, gridBagConstraints);

        jLabel_22.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_22.setText("2048");
        jLabel_22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jLabel_22, gridBagConstraints);

        jLabel_23.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_23.setText("2048");
        jLabel_23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jLabel_23, gridBagConstraints);

        jLabel_24.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_24.setText("2048");
        jLabel_24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jLabel_24, gridBagConstraints);

        jLabel_30.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_30.setText("2048");
        jLabel_30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jLabel_30, gridBagConstraints);

        jLabel_31.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_31.setText("2048");
        jLabel_31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jLabel_31, gridBagConstraints);

        jLabel_32.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_32.setText("2048");
        jLabel_32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jLabel_32, gridBagConstraints);

        jLabel_33.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_33.setText("2048");
        jLabel_33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jLabel_33, gridBagConstraints);

        jLabel_34.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_34.setText("2048");
        jLabel_34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jLabel_34, gridBagConstraints);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(score)
                .addGap(0, 87, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel4.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        this.store_values_from_label();
        this.shift_down();
        
        for(int i=0;i<5;++i)
        {
            for(int j=4;j>=1;--j)
            {
                if(values[j][i]==values[j-1][i])
                {
                    score_user+=values[j][i];
                    values[j][i]=2*values[j][i];
                    values[j-1][i]=0;
                }
            }
        }
        
        score.setText(score_user+"");
        this.shift_down();
       // this.show_values_into_labels();
        this.generating_new_number();
        this.show_values_into_labels();
        this.check_for_2048();
        
    }                                       

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
        
        this.store_values_from_label();// storing values from label to values[][]
        
        this.shift_left();// shifting the whole array (left)
        
         for(int i=0;i<5;++i)// comparing the values
        {
            for(int j=0;j<4;++j)
            {
                if(values[i][j]==values[i][j+1])
                {
                    score_user+=values[i][j];
                    values[i][j]=2*values[i][j];
                    values[i][j+1]=0;
                    
                  //  score.setText(score_user+"");
                    
                }
            }
        }
        score.setText(score_user+""); 
        this.shift_left();
        //this.show_values_into_labels();// values[][] into labels
        this.generating_new_number();
        this.show_values_into_labels();
        this.check_for_2048();
        
        
        
    }                                       

    private void btnUPActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
         this.store_values_from_label();
         this.shift_up();
         
         for(int i=0;i<5;++i)
         {
             for(int j=0;j<4;++j)
             {
                if(values[j][i]==values[j+1][i])
                {
                    score_user+=values[j][i];
                    values[j][i]=2*values[j][i];
                    values[j+1][i]=0;
                }
             }
         }
         
         score.setText(score_user+"");
         this.shift_up();
         //this.show_values_into_labels();
         this.generating_new_number();
         this.show_values_into_labels();
         this.check_for_2048();
       
        
        
    }                                     

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        this.store_values_from_label();
        this.shift_right();
        
        for(int i=0;i<5;++i)
        {
            for(int j=4;j>=1;--j)
            {
                if(values[i][j]==values[i][j-1])
                {
                    score_user+=values[i][j];
                    values[i][j]=2*values[i][j];
                    values[i][j-1]=0;
                }
            }
        }
            
        score.setText(score_user+"");
        this.shift_right();
       // this.show_values_into_labels();
        this.generating_new_number();
        this.show_values_into_labels();
        this.check_for_2048();
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }
    private void store_values_from_label()
    {
        
        for(int i=0;i<5;++i)
        {
            for(int j=0;j<5;++j)
            {
                if(jl[i][j].getText().equals(""))
                {
                    values[i][j]=0;
                }
                else
                {
                    values[i][j]=Integer.parseInt(jl[i][j].getText());
                }
            }
        }
    
        
    }
    void assign_respective_labels()
    {
        jl[0][0]=jLabel_00;
        jl[0][1]=jLabel_01;
        jl[0][2]=jLabel_02;
        jl[0][3]=jLabel_03;
        jl[0][4]=jLabel_04;
     //****************************************
        jl[1][0]=jLabel_10;
        jl[1][1]=jLabel_11;
        jl[1][2]=jLabel_12;
        jl[1][3]=jLabel_13;
        jl[1][4]=jLabel_14;
     //****************************************   
        jl[2][0]=jLabel_20;
        jl[2][1]=jLabel_21;
        jl[2][2]=jLabel_22;
        jl[2][3]=jLabel_23;
        jl[2][4]=jLabel_24;
     //****************************************   
        jl[3][0]=jLabel_30;
        jl[3][1]=jLabel_31;
        jl[3][2]=jLabel_32;
        jl[3][3]=jLabel_33;
        jl[3][4]=jLabel_34;
     //****************************************   
        jl[4][0]=jLabel_40;
        jl[4][1]=jLabel_41;
        jl[4][2]=jLabel_42;
        jl[4][3]=jLabel_43;
        jl[4][4]=jLabel_44;
        
    }
    void shift_left()
    {
        
        int [] a=new int[5]; int t=0;
        
        for(int i=0;i<5;++i)
        {
            for(int j=0;j<5;++j)
            {
                a[j]=values[i][j];
            }
            for(int k=0;k<5;++k)
            {
                if(a[k]!=0)
                {
                    values[i][t]=a[k];
                    ++t;
                }
                else
                {
                    
                }
            }
            while(t<=4)
            {
                values[i][t]=0;
                ++t;
            }
            t=0;
        }
        
    }
    void shift_right()
    {
        
        int [] a=new int[5]; 
        int t=4;
        for(int i=0;i<5;++i)
        {
            for(int j=4;j>=0;--j)
            {
                a[j]=values[i][j];// storing the values
            }
            for(int k=4;k>=0;--k)// now performing the shift operation
            {
                if(a[k]!=0)
                {
                    values[i][t]=a[k];
                    --t;
                }
                else
                {
                    
                }
            }
            while(t>=0)
            {
                values[i][t]=0;
                --t;
            }
            t=4;
        }
        
    }
    void shift_up()
    {
       int []a=new int[5];
       int t=0;
       for(int i=0;i<5;++i)
       {
           for(int j=0;j<5;++j)
           {
               a[j]=values[j][i];
           }
           for(int k=0;k<5;++k)
           {
               if(a[k]!=0)
               {
                   values[t][i]=a[k];
                   ++t;
               }
           }
           while(t<=4)
           {
               values[t][i]=0;
               ++t;
           }
           t=0;
       }
       
    }
    void shift_down()
    {
        int []a=new int[5];
        int t=4;
        for(int i=0;i<5;++i)
        {
            for(int j=0;j<5;++j)
            {
                a[j]=values[j][i];
            }
            for(int k=4;k>=0;--k)
            {
                if(a[k]!=0)
                {
                    values[t][i]=a[k];
                    --t;
                }
            }
            while(t>=0)
            {
                values[t][i]=0;
                --t;
            }
            t=4;
        }
    }
    private void generating_new_number()
    {
        boolean fl=false;
        boolean continue_to_generate=false;
        
        for(int i=0;i<5;++i)
        {
            for(int j=0;j<5;++j)
            {
                if(values[i][j]==0)
                {
                    continue_to_generate=true;
                    fl=true;
                    break;
                }
            }
            if(continue_to_generate)
            {
                break;
            }
        }
        while(fl)
        {
        int i=rd.nextInt(5);
        int j=rd.nextInt(5);
        if(values[i][j]==0)
        {
           // jl[i][j].setText("2");
            values[i][j]=2;
            fl=false;
        }
        }
    }
    private void check_for_2048()
    {
        boolean game_reamaining=false;
       for(int i=0;i<5;++i)
       {
           for(int j=0;j<5;++j)
           {
               if(values[i][j]==0)
               {
                   game_reamaining=true;
                   
                   break;
               }
              
           }
           if(game_reamaining)
           {
               break;
           }
       }
       if(!game_reamaining)
       { boolean check_2048=false;
           for(int i=0;i<5;++i)
       {
           for(int j=0;j<5;++j)
           {
               if(values[i][j]==2048)
               {
                   check_2048=true;
                   break;
               }
              
           }
       }
           if(check_2048)
           {
               System.out.println("Yes you are the Intelligent");
               Game_completed g=new Game_completed();
               
               this.setVisible(false);
               
               
               
               
           }
           else
           {
               System.out.println("Sorry GAME OVER");
               Game_over c=new Game_over();
               this.setVisible(false);
               
           }
       }
    }
    private void show_values_into_labels()
    {
        for(int i=0;i<5;++i)
        {
            for(int j=0;j<5;++j)
            {
               try
               {
                if(values[i][j]==0)
                {
                    jl[i][j].setText("");
                    
                    //Thread.sleep(5);
                }
                   else 
                {    
                    jl[i][j].setText(values[i][j]+"");
                       Thread.sleep(5);
                    /*        switch(values[i][j])
                     {
                        
                         case 2:jl[i][j].setBackground(c2);break;
                         case 4:jl[i][j].setBackground(c4);break;
                         case 8:jl[i][j].setBackground(c8);break;
                         case 16:jl[i][j].setBackground(c16);break;
                         case 32:jl[i][j].setBackground(c32);break;
                         case 64:jl[i][j].setBackground(c64);break;
                         case 128:jl[i][j].setBackground(c128);break;
                         case 256:jl[i][j].setBackground(c256);break;
                         case 512:jl[i][j].setBackground(c512);break;
                         case 1024:jl[i][j].setBackground(c1024);break;
                         case 2048:jl[i][j].setBackground(c2048);break;

                     */
                      
                      
                }
               }
               catch(InterruptedException e)
               {
                   e.printStackTrace();
               }
               
                
            }
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnUP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_00;
    private javax.swing.JLabel jLabel_01;
    private javax.swing.JLabel jLabel_02;
    private javax.swing.JLabel jLabel_03;
    private javax.swing.JLabel jLabel_04;
    private javax.swing.JLabel jLabel_10;
    private javax.swing.JLabel jLabel_11;
    private javax.swing.JLabel jLabel_12;
    private javax.swing.JLabel jLabel_13;
    private javax.swing.JLabel jLabel_14;
    private javax.swing.JLabel jLabel_20;
    private javax.swing.JLabel jLabel_21;
    private javax.swing.JLabel jLabel_22;
    private javax.swing.JLabel jLabel_23;
    private javax.swing.JLabel jLabel_24;
    private javax.swing.JLabel jLabel_30;
    private javax.swing.JLabel jLabel_31;
    private javax.swing.JLabel jLabel_32;
    private javax.swing.JLabel jLabel_33;
    private javax.swing.JLabel jLabel_34;
    private javax.swing.JLabel jLabel_40;
    private javax.swing.JLabel jLabel_41;
    private javax.swing.JLabel jLabel_42;
    private javax.swing.JLabel jLabel_43;
    private javax.swing.JLabel jLabel_44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JLabel score;
    // End of variables declaration                   
}
