
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arihant
 */
public class Frontframe extends javax.swing.JFrame {
  String Selectedcountry="";
  String Stateslect="";
    

   
    public Frontframe() {
        initComponents();
        DefaultComboBoxModel cmodel=(DefaultComboBoxModel) CountryBox.getModel();
      
      
        cmodel.addElement("India");
        cmodel.addElement("USA");
        cmodel.addElement("UK");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CountryBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        StateBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        CityBox = new javax.swing.JComboBox();
        Submitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Country");

        jLabel2.setFont(new java.awt.Font("SimHei", 0, 29)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Your Place of origin");

        CountryBox.setFont(new java.awt.Font("Vrinda", 0, 13)); // NOI18N
        CountryBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CountryBoxItemStateChanged(evt);
            }
        });
        CountryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" State");

        StateBox.setFont(new java.awt.Font("Vrinda", 0, 13)); // NOI18N
        StateBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StateBoxItemStateChanged(evt);
            }
        });
        StateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("City");

        CityBox.setFont(new java.awt.Font("Vrinda", 0, 13)); // NOI18N

        Submitbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Submitbtn.setText("Submit");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CountryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StateBox, 0, 111, Short.MAX_VALUE)))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(Submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(Submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CountryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryBoxActionPerformed
         Selectedcountry=(String)CountryBox.getSelectedItem();
        System.out.println(Selectedcountry+"");
        DefaultComboBoxModel cm1=(DefaultComboBoxModel) StateBox.getModel();
        if(Selectedcountry.equals("India"))
       {cm1.addElement("Madhya Pradesh");
       cm1.addElement("Gujarat");
       cm1.addElement("Karnataka");
       }
       
        else if(Selectedcountry.equals("USA"))
        {cm1.removeAllElements();
            cm1.addElement("Virginia");
            cm1.addElement("Lebanon");
            System.out.println("hi");
        }
        else if(Selectedcountry.equals("UK"))
        {cm1.removeAllElements();
            cm1.addElement("Warwickshire");
            cm1.addElement("Yorkshire");
            cm1.addElement("Derbyshire");
        }
     
    
     
    }//GEN-LAST:event_CountryBoxActionPerformed

    private void StateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateBoxActionPerformed
         DefaultComboBoxModel cm2=(DefaultComboBoxModel) CityBox.getModel();
          Stateslect=(String)StateBox.getSelectedItem();
         if(Stateslect.equals("Madhya Pradesh"))
         {
             cm2.removeAllElements();
             cm2.addElement("Indore");
             cm2.addElement("Bhopal");
         }
        else if(Stateslect.equals("Gujarat"))
         {
             cm2.removeAllElements();
             cm2.addElement("Ahemdabad");
             cm2.addElement("Baroda");
         }
        else if(Stateslect.equalsIgnoreCase("karnataka"))
         {
             cm2.removeAllElements();
             cm2.addElement("Banglore");
             cm2.addElement("Mysore");
         }
        else if(Stateslect.equalsIgnoreCase("Virginia"))
         {
             cm2.removeAllElements();
             cm2.addElement("NewYork");
             
         }
        else if(Stateslect.equalsIgnoreCase("Debyshire"))
        {
            cm2.removeAllElements();
            cm2.addElement("London");
            cm2.addElement("Nottingham");
        }
    }//GEN-LAST:event_StateBoxActionPerformed

    private void CountryBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CountryBoxItemStateChanged
     // TODO add your handling code here:
    }//GEN-LAST:event_CountryBoxItemStateChanged

    private void StateBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StateBoxItemStateChanged
              // TODO add your handling code here:
    }//GEN-LAST:event_StateBoxItemStateChanged

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed

        JOptionPane.showConfirmDialog(this,(String)CountryBox.getSelectedItem()+"\n"+(String)StateBox.getSelectedItem()+"\n"+(String)CityBox.getSelectedItem());        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frontframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CityBox;
    private javax.swing.JComboBox CountryBox;
    private javax.swing.JComboBox StateBox;
    private javax.swing.JButton Submitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
