/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class AcIcons extends javax.swing.JFrame {

    /**
     * Creates new form AcIcons
     */
   int temperatureValue;
    public AcIcons() {
        initComponents();
        temperatureValue=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temperature = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        plusTemperature = new javax.swing.JLabel();
        minus_temperature = new javax.swing.JLabel();
        temp_value = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        temperature.setBackground(new java.awt.Color(0, 153, 204));
        temperature.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        temperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temperature.setText("TEMPERATURE");
        temperature.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        temperature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temperatureMouseClicked(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 153, 204));
        back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        plusTemperature.setBackground(new java.awt.Color(0, 153, 204));
        plusTemperature.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        plusTemperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plusTemperature.setText("+");
        plusTemperature.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        plusTemperature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusTemperatureMouseClicked(evt);
            }
        });

        minus_temperature.setBackground(new java.awt.Color(0, 153, 204));
        minus_temperature.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        minus_temperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minus_temperature.setText("-");
        minus_temperature.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        minus_temperature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus_temperatureMouseClicked(evt);
            }
        });

        temp_value.setBackground(new java.awt.Color(0, 153, 204));
        temp_value.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        temp_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temp_value.setText("0");
        temp_value.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        temp_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temp_valueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plusTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minus_temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temp_value, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(plusTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(minus_temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(temp_value, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperatureMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void plusTemperatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusTemperatureMouseClicked
        // TODO add your handling code here:
        ++temperatureValue;
        temp_value.setText(temperatureValue+"");
    }//GEN-LAST:event_plusTemperatureMouseClicked

    private void minus_temperatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_temperatureMouseClicked
        // TODO add your handling code here:
        --temperatureValue;
        temp_value.setText(temperatureValue+"");
    }//GEN-LAST:event_minus_temperatureMouseClicked

    private void temp_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp_valueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_temp_valueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcIcons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel minus_temperature;
    private javax.swing.JLabel plusTemperature;
    private javax.swing.JLabel temp_value;
    private javax.swing.JLabel temperature;
    // End of variables declaration//GEN-END:variables
}
