/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ScreenStb extends javax.swing.JFrame {

    /**
     * Creates new form ScreenStb
     */
    public ScreenStb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tataSky = new javax.swing.JLabel();
        airtel = new javax.swing.JLabel();
        videocon = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tataSky.setBackground(new java.awt.Color(0, 153, 204));
        tataSky.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        tataSky.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tataSky.setText("Tata Sky");
        tataSky.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        tataSky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tataSkyMouseClicked(evt);
            }
        });

        airtel.setBackground(new java.awt.Color(0, 153, 204));
        airtel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        airtel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        airtel.setText("Airtel");
        airtel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        airtel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airtelMouseClicked(evt);
            }
        });

        videocon.setBackground(new java.awt.Color(0, 153, 204));
        videocon.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        videocon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        videocon.setText("Videocon");
        videocon.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        videocon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoconMouseClicked(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 153, 204));
        back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tataSky, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airtel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(videocon, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tataSky, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airtel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videocon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void tataSkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tataSkyMouseClicked
        // TODO add your handling code here:
        TvIcons tvicons=new TvIcons();
        tvicons.setVisible(true);
    }//GEN-LAST:event_tataSkyMouseClicked

    private void airtelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airtelMouseClicked
        // TODO add your handling code here:
        TvIcons tvicons=new TvIcons();
        tvicons.setVisible(true);
    }//GEN-LAST:event_airtelMouseClicked

    private void videoconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoconMouseClicked
        // TODO add your handling code here:
        TvIcons tvicons=new TvIcons();
        tvicons.setVisible(true);
    }//GEN-LAST:event_videoconMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airtel;
    private javax.swing.JLabel back;
    private javax.swing.JLabel tataSky;
    private javax.swing.JLabel videocon;
    // End of variables declaration//GEN-END:variables
}
