
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ScreenTv extends javax.swing.JFrame {

    /**
     * Creates new form ScreenTv
     */
    public ScreenTv() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panasonic = new javax.swing.JLabel();
        lg = new javax.swing.JLabel();
        sony = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panasonic.setBackground(new java.awt.Color(0, 153, 204));
        panasonic.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        panasonic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panasonic.setText("Panasonic");
        panasonic.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        panasonic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panasonicMouseClicked(evt);
            }
        });

        lg.setBackground(new java.awt.Color(0, 153, 204));
        lg.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        lg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lg.setText("LG");
        lg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgMouseClicked(evt);
            }
        });

        sony.setBackground(new java.awt.Color(0, 153, 204));
        sony.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        sony.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sony.setText("Sony");
        sony.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        sony.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sonyMouseClicked(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 153, 204));
        back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panasonic, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sony, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panasonic, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sony, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void panasonicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panasonicMouseClicked
        // TODO add your handling code here:
        TvIcons tvicons=new TvIcons();
        tvicons.setVisible(true);
    }//GEN-LAST:event_panasonicMouseClicked

    private void lgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseClicked
        // TODO add your handling code here:
        TvIcons tvicons=new TvIcons();
        tvicons.setVisible(true);
    }//GEN-LAST:event_lgMouseClicked

    private void sonyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sonyMouseClicked
        // TODO add your handling code here:
        TvIcons tvicons=new TvIcons();
        tvicons.setVisible(true);
    }//GEN-LAST:event_sonyMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel panasonic;
    private javax.swing.JLabel sony;
    // End of variables declaration//GEN-END:variables
}
