/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ScreenAc extends javax.swing.JFrame {

    /**
     * Creates new form ScreenAc
     */
    public ScreenAc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lg = new javax.swing.JLabel();
        samsung = new javax.swing.JLabel();
        hitachi = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lg.setBackground(new java.awt.Color(0, 153, 204));
        lg.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        lg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lg.setText("LG");
        lg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgMouseClicked(evt);
            }
        });

        samsung.setBackground(new java.awt.Color(0, 153, 204));
        samsung.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        samsung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        samsung.setText("Samsung");
        samsung.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        samsung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                samsungMouseClicked(evt);
            }
        });

        hitachi.setBackground(new java.awt.Color(0, 153, 204));
        hitachi.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        hitachi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hitachi.setText("Hitachi");
        hitachi.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        hitachi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitachiMouseClicked(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 153, 204));
        back.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(samsung, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hitachi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(samsung, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitachi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void lgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseClicked
        // TODO add your handling code here:
        AcIcons acicons=new AcIcons();
        acicons.setVisible(true);
    }//GEN-LAST:event_lgMouseClicked

    private void samsungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_samsungMouseClicked
        // TODO add your handling code here:
        AcIcons acicons=new AcIcons();
        acicons.setVisible(true);
    }//GEN-LAST:event_samsungMouseClicked

    private void hitachiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitachiMouseClicked
        // TODO add your handling code here:
        AcIcons acicons=new AcIcons();
        acicons.setVisible(true);
    }//GEN-LAST:event_hitachiMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel hitachi;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel samsung;
    // End of variables declaration//GEN-END:variables
}
