/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class TvIcons extends javax.swing.JFrame {

    /**
     * Creates new form TvIcons
     */
    int volume_value;
    int channel_value;
    public TvIcons() {
        initComponents();
        volume_value=0;
        channel_value=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plus_volume = new javax.swing.JLabel();
        volume_text = new javax.swing.JLabel();
        volume = new javax.swing.JLabel();
        channel = new javax.swing.JLabel();
        plus_channel = new javax.swing.JLabel();
        minus_channel = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        channel_text = new javax.swing.JLabel();
        minus_volume = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plus_volume.setBackground(new java.awt.Color(0, 153, 204));
        plus_volume.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        plus_volume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plus_volume.setText("+");
        plus_volume.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        plus_volume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus_volumeMouseClicked(evt);
            }
        });

        volume_text.setBackground(new java.awt.Color(0, 153, 204));
        volume_text.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        volume_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volume_text.setText("00");
        volume_text.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        volume_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volume_textMouseClicked(evt);
            }
        });

        volume.setBackground(new java.awt.Color(0, 153, 204));
        volume.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        volume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volume.setText("VOLUME");
        volume.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        volume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumeMouseClicked(evt);
            }
        });

        channel.setBackground(new java.awt.Color(0, 153, 204));
        channel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        channel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        channel.setText("CHANNEL");
        channel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        channel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channelMouseClicked(evt);
            }
        });

        plus_channel.setBackground(new java.awt.Color(0, 153, 204));
        plus_channel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        plus_channel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plus_channel.setText("+");
        plus_channel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        plus_channel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus_channelMouseClicked(evt);
            }
        });

        minus_channel.setBackground(new java.awt.Color(0, 153, 204));
        minus_channel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        minus_channel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minus_channel.setText("-");
        minus_channel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        minus_channel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus_channelMouseClicked(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(0, 153, 204));
        back_btn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        back_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_btn.setText("BACK");
        back_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        channel_text.setBackground(new java.awt.Color(0, 153, 204));
        channel_text.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        channel_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        channel_text.setText("000");
        channel_text.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        channel_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channel_textMouseClicked(evt);
            }
        });

        minus_volume.setBackground(new java.awt.Color(0, 153, 204));
        minus_volume.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        minus_volume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minus_volume.setText("-");
        minus_volume.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));
        minus_volume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus_volumeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(channel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus_channel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minus_channel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minus_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(volume_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(channel_text, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plus_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volume_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minus_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minus_channel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus_channel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(channel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(channel_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plus_volumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus_volumeMouseClicked

        // TODO add your handling code here:
        ++volume_value;
        volume_text.setText(volume_value+"");
        
        

    }//GEN-LAST:event_plus_volumeMouseClicked

    private void volume_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volume_textMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_volume_textMouseClicked

    private void volumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeMouseClicked

    private void channelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_channelMouseClicked

    private void plus_channelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus_channelMouseClicked
        // TODO add your handling code here:
        ++channel_value;
        channel_text.setText(channel_value+"");
    }//GEN-LAST:event_plus_channelMouseClicked

    private void minus_channelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_channelMouseClicked
        // TODO add your handling code here:
        --channel_value;
        channel_text.setText(channel_value+"");
    }//GEN-LAST:event_minus_channelMouseClicked

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_back_btnMouseClicked

    private void channel_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channel_textMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_channel_textMouseClicked

    private void minus_volumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_volumeMouseClicked
        // TODO add your handling code here:
        --volume_value;
        volume_text.setText(volume_value+"");
    }//GEN-LAST:event_minus_volumeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TvIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TvIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TvIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TvIcons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TvIcons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_btn;
    private javax.swing.JLabel channel;
    private javax.swing.JLabel channel_text;
    private javax.swing.JLabel minus_channel;
    private javax.swing.JLabel minus_volume;
    private javax.swing.JLabel plus_channel;
    private javax.swing.JLabel plus_volume;
    private javax.swing.JLabel volume;
    private javax.swing.JLabel volume_text;
    // End of variables declaration//GEN-END:variables
}
