
import javafx.scene.text.FontPosture;
import javax.swing.DefaultComboBoxModel;
import java.awt.*;


public class Font1 extends javax.swing.JFrame {
    GraphicsEnvironment e = GraphicsEnvironment.getLocalGraphicsEnvironment();
    java.awt.Font fonts[] = e.getAllFonts();
    String fo;
    int sty;
     java.awt.Font f=null;
     int size;
    
    
    
    
    

    /**
     * Creates new form Font
     */
    public Font1() {
        initComponents();
        DefaultComboBoxModel sl=(DefaultComboBoxModel) Style.getModel();
        DefaultComboBoxModel ft=(DefaultComboBoxModel) Fontbox.getModel();
         for (java.awt.Font f : fonts) {
           ft.addElement(f.getFontName());
    }
         sl.addElement("Plain");
         sl.addElement("BOLD");
         sl.addElement("ITALIC");
         sty=0;
         size=18;
         fo="ARIAL";
         f=new java.awt.Font(fo,java.awt.Font.PLAIN,size);
         TextField1.setFont(f);
         //this.setTitle(Fontbox.getSelectedItem()+"");
         this.setVisible(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SizeSpinner = new javax.swing.JSpinner();
        Style = new javax.swing.JComboBox();
        Fontbox = new javax.swing.JComboBox();
        TextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SizeSpinner.setValue(18);
        SizeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SizeSpinnerStateChanged(evt);
            }
        });

        Style.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StyleItemStateChanged(evt);
            }
        });

        Fontbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FontboxItemStateChanged(evt);
            }
        });

        TextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField1.setText("This is your text");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIZE");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STYLE");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FONT");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Style, javax.swing.GroupLayout.Alignment.TRAILING, 0, 124, Short.MAX_VALUE)
                    .addComponent(Fontbox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Style, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fontbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FontboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FontboxItemStateChanged
        fo=  (String) Fontbox.getSelectedItem();
       this.setTitle(fo);
       //f = new java.awt.Font(fo, java.awt.Font.BOLD, size);
       //TextField1.setFont(f);
       if(sty==0)        
{f = new java.awt.Font(fo, java.awt.Font.PLAIN, size);
       TextField1.setFont(f);}
else if(sty==1)
{f=new java.awt.Font(fo,java.awt.Font.BOLD,size);
TextField1.setFont(f);
}
else if(sty==2)
    {f=new java.awt.Font(fo,java.awt.Font.ITALIC,size);
TextField1.setFont(f);
}
       

    }//GEN-LAST:event_FontboxItemStateChanged

    private void StyleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StyleItemStateChanged
        sty=Style.getSelectedIndex();

if(sty==0)        
{f = new java.awt.Font(fo, java.awt.Font.PLAIN, size);
       TextField1.setFont(f);}
else if(sty==1)
{f=new java.awt.Font(fo,java.awt.Font.BOLD,size);
TextField1.setFont(f);
}
else if(sty==2)
    {f=new java.awt.Font(fo,java.awt.Font.ITALIC,size);
TextField1.setFont(f);
}
    }//GEN-LAST:event_StyleItemStateChanged

    private void SizeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SizeSpinnerStateChanged
       size=(int) SizeSpinner.getValue();
       f = new java.awt.Font(fo, java.awt.Font.PLAIN, size);
       TextField1.setFont(f);// TODO add your handling code here:
    }//GEN-LAST:event_SizeSpinnerStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//GetFont g=new GetFont(f);
        NotePad.txtNotepad.setFont(f);
       this.setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Font1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Font1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Font1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Font1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Font1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Fontbox;
    private javax.swing.JSpinner SizeSpinner;
    private javax.swing.JComboBox Style;
    public static javax.swing.JTextField TextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
